apiVersion: v1
kind: Pod
metadata:
  name: apache
  labels:
    app: apache
    tier: frontend
## Always use two spaces instead of tab spaces
spec:
  containers:
  - name: apache
    image: httpd # specify full path of using repo other than DockerHub

  ## to add tolerations in pod. All values should be in the "".
  tolerations: 
  - key: app
    operator: Equal
    value: apache
    effect: NoSchedule ## 3 effect values there : NoSchedule,NoExecute,PreferNoSchedule 
