apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
## Always use two spaces instead of tab spaces
spec:
  containers:
  - name: nginx
    image: nginx # specify full path of using repo other than DockerHub

  nodeSelector: 
    size: Large ## To deploy this pod in the specific node, Node has to be labeled size:Large