apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
## Always use two spaces instead of tab spaces
spec:
  containers:
  - name: nginx
    image: nginx # specify full path of using repo other than DockerHub

  ## to add tolerations in pod. All values should be in the "".
  tolerations: 
  - key: app
    operator: Equal
    value: Blue
    effect: NoSchedule ## 3 effect values there : NoSchedule,NoExecute,PreferNoSchedule 

