apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels: ## This label for the replicaset
    app: myapp
    type: front-end

spec:
  template:
    metadata:
      name: myapp-pod
      labels: ## This label for the pod
        app: myapp
        type: front-end
      spec:
        containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end