apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: my-nginx-deploymemt
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: my-nginx-deploymemt
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: my-nginx-deploymemt