apiVersion: v1
kind: Service
metadata: 
  name: myapp-service
spec:
  type: NodePort ## Type of service
  ports:
  - targetPort: 80 # pod port
    port: 80 # Service port / Mandatory field
    NodePort: 30008 # range between 30000-32767 / if not mentioned randomly assign between that range.
  selector:
    app: myapp
    type: front-end